name: CI
on:
  push:
    branches: ["dev"]
  pull_request:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Project setup
        run: npm ci
      - name: Run tests
        run: npm run test:ci
