name: CI
on:
  push:
    branches: ["dev"]
  pull_request:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Project setup
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/jest-report.xml
